version: '2.1'

services:

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    networks:
      - reverse-proxy
    expose:
      - '80'
      - '443'
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_log:/var/log/onlyoffice

networks:
  reverse-proxy:
    external: true

volumes:
  onlyoffice_data:
    external: true
  onlyoffice_log:
    external: true
