version: '2.1'

services:

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    networks:
      - reverse-proxy
    expose:
      - '80'
      - '443'
    volumes:
      - /mnt/volumes/onlyoffice_data/data:/var/www/onlyoffice/Data
      - /mnt/volumes/onlyoffice_log/data:/var/log/onlyoffice

networks:
  reverse-proxy:
    external: true
